package com.pranshu.crudbasic.service.impl;

import com.pranshu.crudbasic.model.Person;
import com.pranshu.crudbasic.repository.PersonRepository;
import com.pranshu.crudbasic.service.PersonService;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class PersonServiceImpl implements PersonService {

    private final PersonRepository personRepository;

    public PersonServiceImpl(PersonRepository personRepository) {
        this.personRepository = personRepository;
    }

    @Override
    public String createPerson(Person person) {
        personRepository.save(person); // The ID is automatically generated by the database
        return "Success";
    }

    @Override
    public void updatePersonDetails(Long PersonID, Person updatedPersonDetails) {
        Person existingPerson = personRepository.findById(PersonID)
                .orElseThrow(() -> new RuntimeException("Person not found with ID: " + PersonID));
        // Update the fields with the new values
        existingPerson.setPersonName(updatedPersonDetails.getPersonName());
        existingPerson.setPersonDepartment(updatedPersonDetails.getPersonDepartment());

        // Save the updated entity
        personRepository.save(existingPerson);
    }


    @Override
    public String deletePerson(Long PersonID) {
        personRepository.deleteById(PersonID);
        return "Success";
    }

    @Override
    public Person getPerson(Long PersonID) {
        return personRepository.findById(PersonID)
                .orElseThrow(() -> new RuntimeException("Person not found with ID: " + PersonID));
    }

    @Override
    public List<Person> getAllPerson() {
        return personRepository.findAll();
    }
}
